auto: true
markdown: rdiscount
permalink: /:year/:month/:day/:title
rdiscount extensions: [smart]

pygments: true

title: 'Prad Nelluru'
author_name : 'Prad Nelluru'
author_email: 'prad.nelluru@gmail.com'

production_url: 'http://pradnelluru.com'

google_analytics_token: 'UA-37235443-1'